apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWItcmVnaXN0cnkub3pvbi5kZXYiOiB7fSwKCQkicmVnaXN0cnkueWFuZGV4Lm5ldCI6IHt9LAoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiV0l4ZEdVNloyaHdYMmg0TW1OcFRtZENhM041V0ROWk1WbHNNV3BQV0RZeVdWRlZTVmgwYVRKeU5VSXlkdz09IgoJCX0KCX0sCgkiY3JlZHNTdG9yZSI6ICJvc3hrZXljaGFpbiIsCgkiY3VycmVudENvbnRleHQiOiAib3Jic3RhY2siCn0K
type: kubernetes.io/dockerconfigjson
